export const DEFAULT_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ORG_ADMIN: "ORG_ADMIN",
  ORG_OWNER: "ORG_OWNER",
  SUPPORT_ADMIN: "SUPPORT_ADMIN",
  REVIEWER: "REVIEWER",
  EXAMINER: "EXAMINER",
  PUBLIC_USER: "PUBLIC_USER",
  CANDIDATE: "CANDIDATE",
  DISPATCH_MANAGER: "DISPATCH_MANAGER",
  ANALYST: "ANALYST",
  PROCTOR: "PROCTOR"
}